sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: '/%sylius_admin.path_name%'


sylius_invoicing_plugin_admin:
    resource: "@SyliusInvoicingPlugin/Resources/config/app/routing/admin_invoicing.yml"
    prefix: '/%sylius_admin.path_name%'
    
sylius_multi_source_inventory_admin:
    resource: "@SyliusMultiSourceInventoryPlugin/config/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'
    
    
sylius_customer_service_admin:
    resource: "@SyliusCustomerServicePlugin/config/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'

sylius_refund:
    resource: "@SyliusRefundPlugin/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

